server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/todo.db
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
